# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeBase2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeBase2
  pod 'SVProgressHUD'
  target 'CodeBase2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeBase2UITests' do
    # Pods for testing
  end

end
